apiVersion: apps/v1
kind: Deployment
metadata:
  name: cisco-aps-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cisco.labels" . | nindent 4 }}
    app.kubernetes.io/name: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "cisco.selectorLabels" "api" | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cisco.selectorLabels" "api" | nindent 8 }}
    spec:
      {{- if .Values.api.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: cisco-aps-secret
          env:
            - name: GIN_MODE
              value: release
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
