apiVersion: v1
kind: Service
metadata:
  name: cisco-aps-ui
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cisco.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "cisco.selectorLabels" "ui" | nindent 4 }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 3000
      protocol: TCP
